### ISSUE TITLE
Failed to get convolution algorithm. This is probably because cuDNN failed to initialize

### ISSUE THREAD

**Issue by purinsat** [arturjordao/PruningNeuralNetworks#2]
Dear @arturjordao, 
I tried to use the idxs_to_pruned function in VIPPruning.py to print out the index of filters of Conv2D that gonna be pruned of my model and I got this error of the fit() function, X = self.conv_net.predict(X)

"tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

Function call stack:
predict_function "

the code I used just 
    input = Input((456, 456, 3))
    pruning_method = VIPPruning(n_comp=n_components, model=model, representation='max', percentage_discard=p)
    layers = layers_to_prune(model)
    idxs = pruning_method.idxs_to_prune(train_ds,train_label, layers)
    print(idxs)

My model is the efficientNET architecture which predicts out to 13 classes. 
The number of train images is 4800 pictures, the shape of input is 456,456,3.
My train labels are the array of 4800 pictures with 13 classes, so the shape is (4800,13)

So, Does conv_net.predict() can use with Multi-label dataset ?

Best regards,
Satthamnuwong Purin

**Comment by arturjordao** [comment]
Dear @PurinSatthamn,

First of all, my apologies for delaying in answer to your issue.
This code works on multi-label datasets. Note that the example consists of a 10-category network (see line 214).
I'm assuming you are using a network (efficient net) as a layer. For example, let A the EfficientNet then
B = Model(input, A.output).
Assuming the code above, I recommend you try to use the VIPPruning by passing only the efficient model. Something like this:

> layers = layers_to_prune(EfficientNet)
> idxs = pruning_method.idxs_to_prune(train_ds,train_label, layers)
> print(idxs)

I believe my current code does not support models as layers.
If this does not solve the problem, I need you to provide me more details regarding the architecture. With your example, I'm not able to create the entire architecture.

Best regards, 
Artur Jordão
